/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as KoLlmsDottxtRouteImport } from './routes/ko/llms[.]txt'
import { Route as KoLlmsFullDottxtRouteImport } from './routes/ko/llms-full[.]txt'
import { Route as DocsChangelogRouteImport } from './routes/docs/changelog'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as KoDocsIndexRouteImport } from './routes/ko/docs/index'
import { Route as KoDocsChangelogRouteImport } from './routes/ko/docs/changelog'
import { Route as KoDocsSplatRouteImport } from './routes/ko/docs/$'

const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoLlmsDottxtRoute = KoLlmsDottxtRouteImport.update({
  id: '/ko/llms.txt',
  path: '/ko/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const KoLlmsFullDottxtRoute = KoLlmsFullDottxtRouteImport.update({
  id: '/ko/llms-full.txt',
  path: '/ko/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChangelogRoute = DocsChangelogRouteImport.update({
  id: '/docs/changelog',
  path: '/docs/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KoDocsIndexRoute = KoDocsIndexRouteImport.update({
  id: '/ko/docs/',
  path: '/ko/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoDocsChangelogRoute = KoDocsChangelogRouteImport.update({
  id: '/ko/docs/changelog',
  path: '/ko/docs/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const KoDocsSplatRoute = KoDocsSplatRouteImport.update({
  id: '/ko/docs/$',
  path: '/ko/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/ko/llms-full.txt': typeof KoLlmsFullDottxtRoute
  '/ko/llms.txt': typeof KoLlmsDottxtRoute
  '/docs/': typeof DocsIndexRoute
  '/ko/': typeof KoIndexRoute
  '/ko/docs/$': typeof KoDocsSplatRoute
  '/ko/docs/changelog': typeof KoDocsChangelogRoute
  '/ko/docs/': typeof KoDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/ko/llms-full.txt': typeof KoLlmsFullDottxtRoute
  '/ko/llms.txt': typeof KoLlmsDottxtRoute
  '/docs': typeof DocsIndexRoute
  '/ko': typeof KoIndexRoute
  '/ko/docs/$': typeof KoDocsSplatRoute
  '/ko/docs/changelog': typeof KoDocsChangelogRoute
  '/ko/docs': typeof KoDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/changelog': typeof DocsChangelogRoute
  '/ko/llms-full.txt': typeof KoLlmsFullDottxtRoute
  '/ko/llms.txt': typeof KoLlmsDottxtRoute
  '/docs/': typeof DocsIndexRoute
  '/ko/': typeof KoIndexRoute
  '/ko/docs/$': typeof KoDocsSplatRoute
  '/ko/docs/changelog': typeof KoDocsChangelogRoute
  '/ko/docs/': typeof KoDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/changelog'
    | '/ko/llms-full.txt'
    | '/ko/llms.txt'
    | '/docs/'
    | '/ko/'
    | '/ko/docs/$'
    | '/ko/docs/changelog'
    | '/ko/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/changelog'
    | '/ko/llms-full.txt'
    | '/ko/llms.txt'
    | '/docs'
    | '/ko'
    | '/ko/docs/$'
    | '/ko/docs/changelog'
    | '/ko/docs'
  id:
    | '__root__'
    | '/'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/api/search'
    | '/docs/$'
    | '/docs/changelog'
    | '/ko/llms-full.txt'
    | '/ko/llms.txt'
    | '/docs/'
    | '/ko/'
    | '/ko/docs/$'
    | '/ko/docs/changelog'
    | '/ko/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsChangelogRoute: typeof DocsChangelogRoute
  KoLlmsFullDottxtRoute: typeof KoLlmsFullDottxtRoute
  KoLlmsDottxtRoute: typeof KoLlmsDottxtRoute
  DocsIndexRoute: typeof DocsIndexRoute
  KoIndexRoute: typeof KoIndexRoute
  KoDocsSplatRoute: typeof KoDocsSplatRoute
  KoDocsChangelogRoute: typeof KoDocsChangelogRoute
  KoDocsIndexRoute: typeof KoDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/llms.txt': {
      id: '/ko/llms.txt'
      path: '/ko/llms.txt'
      fullPath: '/ko/llms.txt'
      preLoaderRoute: typeof KoLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/llms-full.txt': {
      id: '/ko/llms-full.txt'
      path: '/ko/llms-full.txt'
      fullPath: '/ko/llms-full.txt'
      preLoaderRoute: typeof KoLlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/changelog': {
      id: '/docs/changelog'
      path: '/docs/changelog'
      fullPath: '/docs/changelog'
      preLoaderRoute: typeof DocsChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/docs/': {
      id: '/ko/docs/'
      path: '/ko/docs'
      fullPath: '/ko/docs/'
      preLoaderRoute: typeof KoDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/docs/changelog': {
      id: '/ko/docs/changelog'
      path: '/ko/docs/changelog'
      fullPath: '/ko/docs/changelog'
      preLoaderRoute: typeof KoDocsChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/docs/$': {
      id: '/ko/docs/$'
      path: '/ko/docs/$'
      fullPath: '/ko/docs/$'
      preLoaderRoute: typeof KoDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsChangelogRoute: DocsChangelogRoute,
  KoLlmsFullDottxtRoute: KoLlmsFullDottxtRoute,
  KoLlmsDottxtRoute: KoLlmsDottxtRoute,
  DocsIndexRoute: DocsIndexRoute,
  KoIndexRoute: KoIndexRoute,
  KoDocsSplatRoute: KoDocsSplatRoute,
  KoDocsChangelogRoute: KoDocsChangelogRoute,
  KoDocsIndexRoute: KoDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
