/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as KoDocsIndexRouteImport } from './routes/ko/docs/index'
import { Route as KoDocsSplatRouteImport } from './routes/ko/docs/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const KoDocsIndexRoute = KoDocsIndexRouteImport.update({
  id: '/ko/docs/',
  path: '/ko/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoDocsSplatRoute = KoDocsSplatRouteImport.update({
  id: '/ko/docs/$',
  path: '/ko/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/ko/': typeof KoIndexRoute
  '/ko/docs/$': typeof KoDocsSplatRoute
  '/ko/docs/': typeof KoDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs': typeof DocsIndexRoute
  '/ko': typeof KoIndexRoute
  '/ko/docs/$': typeof KoDocsSplatRoute
  '/ko/docs': typeof KoDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/ko/': typeof KoIndexRoute
  '/ko/docs/$': typeof KoDocsSplatRoute
  '/ko/docs/': typeof KoDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/search'
    | '/docs/$'
    | '/docs/'
    | '/ko/'
    | '/ko/docs/$'
    | '/ko/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/search'
    | '/docs/$'
    | '/docs'
    | '/ko'
    | '/ko/docs/$'
    | '/ko/docs'
  id:
    | '__root__'
    | '/'
    | '/api/search'
    | '/docs/$'
    | '/docs/'
    | '/ko/'
    | '/ko/docs/$'
    | '/ko/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
  KoIndexRoute: typeof KoIndexRoute
  KoDocsSplatRoute: typeof KoDocsSplatRoute
  KoDocsIndexRoute: typeof KoDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/docs/': {
      id: '/ko/docs/'
      path: '/ko/docs'
      fullPath: '/ko/docs/'
      preLoaderRoute: typeof KoDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/docs/$': {
      id: '/ko/docs/$'
      path: '/ko/docs/$'
      fullPath: '/ko/docs/$'
      preLoaderRoute: typeof KoDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
  KoIndexRoute: KoIndexRoute,
  KoDocsSplatRoute: KoDocsSplatRoute,
  KoDocsIndexRoute: KoDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
