name: ci
on:
  pull_request:
concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # 4.0.1
        with:
          install_args: 'node'
      - run: corepack enable
      - run: yarn install
      - run: yarn gen:fumadocs
      - run: yarn lint
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # 4.0.1
        with:
          install_args: 'node'
      - run: corepack enable
      - run: yarn install
      - run: yarn format --check
  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # 4.0.1
        with:
          install_args: 'node'
      - run: corepack enable
      - run: yarn install
      - run: yarn check:links
